# Generated by Django 3.1.3 on 2021-11-25 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.CharField(db_column='Stock_id', max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='User_id', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='Email', max_length=30, unique=True)),
                ('nickname', models.CharField(db_column='Nickname', max_length=30, unique=True)),
                ('phone_number', models.CharField(db_column='Phone_number', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('user', models.OneToOneField(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StockInfo.user')),
                ('like', models.CharField(db_column='Like', max_length=1)),
            ],
            options={
                'db_table': 'comment_like',
            },
        ),
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('record_id', models.AutoField(db_column='Record_id', primary_key=True, serialize=False)),
                ('trade_price', models.IntegerField(db_column='Trade_price')),
                ('trade_quantity', models.IntegerField(db_column='Trade_quantity')),
                ('trade_type', models.CharField(db_column='Trade_type', max_length=1)),
                ('trade_date', models.DateTimeField(db_column='Trade_date')),
                ('memo', models.CharField(blank=True, db_column='Memo', max_length=30, null=True)),
                ('stock', models.OneToOneField(db_column='Stock_id', on_delete=django.db.models.deletion.CASCADE, to='StockInfo.stock')),
                ('user', models.OneToOneField(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='StockInfo.user')),
            ],
            options={
                'db_table': 'trade_record',
            },
        ),
        migrations.CreateModel(
            name='DayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='Date')),
                ('open_price', models.IntegerField(db_column='Open_price')),
                ('high_price', models.IntegerField(db_column='High_price')),
                ('low_price', models.IntegerField(db_column='Low_price')),
                ('close_price', models.IntegerField(db_column='Close_price')),
                ('transaction_amount', models.IntegerField(db_column='Transaction_amount')),
                ('rate', models.FloatField(db_column='Rate')),
                ('BPS', models.IntegerField(db_column='BPS')),
                ('PER', models.FloatField(db_column='PER')),
                ('PBR', models.FloatField(db_column='PBR')),
                ('EPS', models.IntegerField(db_column='EPS')),
                ('market_cap', models.IntegerField(db_column='Market_cap')),
                ('stock', models.ForeignKey(db_column='Stock_id', on_delete=django.db.models.deletion.CASCADE, to='StockInfo.stock')),
            ],
            options={
                'db_table': 'day_info',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post_id', models.AutoField(db_column='Post_id', primary_key=True, serialize=False)),
                ('content', models.CharField(db_column='Content', max_length=30)),
                ('create_time', models.DateTimeField(db_column='Create_time')),
                ('stock', models.OneToOneField(db_column='Stock_id', on_delete=django.db.models.deletion.CASCADE, to='StockInfo.stock')),
                ('user', models.OneToOneField(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='StockInfo.user')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='InterestedIn',
            fields=[
                ('user', models.OneToOneField(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StockInfo.user')),
                ('stock', models.OneToOneField(db_column='Stock_id', on_delete=django.db.models.deletion.CASCADE, to='StockInfo.stock')),
            ],
            options={
                'db_table': 'interested_in',
            },
        ),
        migrations.AddConstraint(
            model_name='dayinfo',
            constraint=models.UniqueConstraint(fields=('stock', 'date'), name='unique day info'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='post',
            field=models.OneToOneField(db_column='Post_id', on_delete=django.db.models.deletion.CASCADE, to='StockInfo.comment'),
        ),
        migrations.AlterUniqueTogether(
            name='interestedin',
            unique_together={('user', 'stock')},
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'post')},
        ),
    ]
