# Generated by Django 3.2.9 on 2021-11-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('Stock_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Price_now', models.IntegerField()),
                ('Last_update', models.DateTimeField()),
            ],
        ),
    ]
