# Generated by Django 3.2.9 on 2021-11-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('Create_time', models.DateTimeField()),
                ('Stock_id', models.ForeignKey(db_column='Stock_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='StockInfo.stock')),
            ],
        ),
    ]
