# Generated by Django 3.2.9 on 2021-11-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockInfo', '0003_interested_in_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Create_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Post_id',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Stock_id',
            new_name='stock_id',
        ),
        migrations.RenameField(
            model_name='interested_in',
            old_name='Stock_id',
            new_name='stock_id',
        ),
        migrations.RenameField(
            model_name='interested_in',
            old_name='User_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='Last_update',
            new_name='last_update',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='Price_now',
            new_name='price_now',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='Stock_id',
            new_name='stock_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_id',
            new_name='user_id',
        ),
    ]
